source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'STXInstagramFeedView_Example', :exclusive => true do
  pod "STXInstagramFeedView", :path => "../"
  pod 'KZPropertyMapper'
end

target 'STXInstagramFeedView_Tests', :exclusive => true do
  pod "STXInstagramFeedView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
