source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/rinat-enikeev/CocoaPodsSpecs.git'
use_frameworks!
inhibit_all_warnings!

target 'STXInstagramFeedView_Example', :exclusive => true do
  pod "STXInstagramFeedView", :path => "../"
  pod 'KZPropertyMapper'
  pod 'InstaModel'
  pod 'InstaKit'
end

target 'STXInstagramFeedView_Tests', :exclusive => true do
  pod "STXInstagramFeedView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
